services:
  postgres:
    image: postgres:16-alpine
    container_name: sistema-assinaturas-postgres
    environment:
      POSTGRES_DB: assinaturas
      POSTGRES_USER: assinaturas
      POSTGRES_PASSWORD: assinaturas
    ports:
      - "5433:5432"
    volumes:
      - assinaturas_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: sistema-assinaturas-redis
    ports:
      - "6379:6379"
    volumes:
      - assinaturas_redis_data:/data

volumes:
  assinaturas_postgres_data:
  assinaturas_redis_data:
